[theme]
name = "nord"
fg = "#d8dee9"
bg = "#2e3440"
border = "#4c566a"
border_active = "#88c0d0"
status_bg = "#3b4252"
status_fg = "#d8dee9"
tab_active_bg = "#88c0d0"
tab_active_fg = "#2e3440"
tab_inactive_fg = "#4c566a"
selection = "#434c5e"
search_match = "#ebcb8b"
broadcast_indicator = "#bf616a"
copy_mode_indicator = "#a3be8c"
