[theme]
name = "solarized-dark"
fg = "#93a1a1"
bg = "#002b36"
border = "#586e75"
border_active = "#268bd2"
status_bg = "#002b36"
status_fg = "#93a1a1"
tab_active_bg = "#268bd2"
tab_active_fg = "#002b36"
tab_inactive_fg = "#657b83"
selection = "#073642"
search_match = "#b58900"
broadcast_indicator = "#dc322f"
copy_mode_indicator = "#859900"
